package ia.desafio.backend.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Inscripcion")
public class Inscripcion implements Serializable {

	private static final long serialVersionUID = 1L;

	private String inscripcionId;
	private String nombre;
	private String rut;
	private String correo;
	private String telefono;

	@DynamoDBHashKey(attributeName = "InscripcionId")
	@DynamoDBAutoGeneratedKey
	public String getInscripcionId() {
		return inscripcionId;
	}

	public void setInscripcionId(String inscripcionId) {
		this.inscripcionId = inscripcionId;
	}

	@DynamoDBAttribute
	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	@DynamoDBAttribute
	public String getCorreo() {
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@DynamoDBAttribute
	public String getRut() {
		return rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}
	
	@DynamoDBAttribute
	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
	
}
